sitewoman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from women.views import page_not_found

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("women.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("__debug__/", include("debug_toolbar.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Известные женщины"
handler404 = page_not_found

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginUsers.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path("profile/", views.ProfileUser.as_view(), name="profile"),
    path("passwor-change/", views.UserPasswordChangeView.as_view(), name="password_change"),
    path("password-change/done/", PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),
    path("password-reset/", PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path("password-reset/done/", PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name="password_reset_done"),
    path("password-reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset/complete/", PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),



]

users/models.py
from django.db import models

# Create your models here.

def func(x):
    return x*2

@decorator
def func1()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин: ", widget=forms.TextInput(attrs={"class": "form-input"}))
    password = forms.CharField(label="Пароль: ", widget=forms.PasswordInput(attrs={"class": "form-input"}))

    class Meta:
        model = get_user_model()
        fields = ["username", "password"]


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='username', widget=forms.TextInput(attrs={"class": "form-input"}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={"class": "form-input"}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={"class": "form-input"}))

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]
        labels = {
            "email": "E-mail",
            "first_name": "Имя",
            "last_name": "Фамилия",
        }
        widgets = {
            "email": forms.TextInput(attrs={"class": "form-input"}),
            "first_name": forms.TextInput(attrs={"class": "form-input"}),
            "last_name": forms.TextInput(attrs={"class": "form-input"})
        }

    # def clean_password2(self):
    #     cd = self.cleaned_data
    #     if cd["password"] != cd["password2"]:
    #         raise forms.ValidationError("Пароли не совпадают")
    #     return cd["password"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с такой почтой уже существует")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label="Логин: ",
                               widget=forms.TextInput(attrs={"class": "form-input"}))
    email = forms.CharField(disabled=True, label="E-mail: ", widget=forms.TextInput(attrs={"class": "form-input"}))

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "first_name", "last_name"]
        labels = {
            "first_name": "Имя",
            "last_name": "Фамилия"
        }
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-input"}),
            "last_name": forms.TextInput(attrs={"class": "form-input"})
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    new_password2 = forms.CharField(label="Повтор нового пароля",
                                    widget=forms.PasswordInput(attrs={"class": "form-input"}))

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth import get_user_model
from django.http.response import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm

from django.shortcuts import render


# Create your views here.


class ProfileUser(LoginRequiredMixin, UpdateView):
    form_class = ProfileUserForm
    template_name = "users/profile.html"
    extra_context = {
        "title": "Профиль пользователя"
    }

    def get_success_url(self):
        return reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    model = get_user_model()
    template_name = "users/register.html"
    extra_context = {
        "title": "Регистрация"
    }
    success_url = reverse_lazy("users:login")


# def register_user(request):
#     if request.method == "POST":
#         form = RegisterUserForm(request.POST)
#         if form.is_valid():
#             form.instance.set_password(form.cleaned_data["password"])
#             form.save()
#             return render(request, "users/register_done.html")
#     else:
#         form = RegisterUserForm()
#     return render(request, 'users/register.html', {"form": form})


class LoginUsers(LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"
    extra_context = {
        "title": "Авторизация"
    }
    #
    # def get_success_url(self):
    #     return reverse_lazy("home")

# def login_users(request):
#     if request.method == "POST":
#         form = LoginUserForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd["username"],
#                                 password=cd["password"])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse("home"))
#
#     form = LoginUserForm()
#     return render(request, "users/login.html",
#                   context={
#                       "title": "Авторизация",
#                       "form": form
#                   })


# def logout_users(request):
#     logout(request)
#     return HttpResponseRedirect(reverse("users:login"))



class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change.html"

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="f.id_for_label">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>
<p><a href="{% url 'users:password_reset' %}">Сбросить пароль</a></p>
{% endblock %}

users/templates/users/password_change.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="f.id_for_label">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

<title>Пароль успешно изменен</title>
{% block content %}

    <h1>Пароль успешно изменен</h1>
    <p>Вы успешно изменили пароль.<a href="{% url 'users:profile' %}"> Вернутся в личный кабинет</a></p>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="f.id_for_label">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно поменян!</h1>
<p>Вы успешно поменяли пароль! Чтобы перейти в личный кабинет, нажмите <a href="{% url 'users:profile' %}">здесь.</a></p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% enxtends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="f.id_for_label">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}


<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="f.id_for_label">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>

<hr>
<p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="f.id_for_label">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Зарегистрироваться</button></p>
</form>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пользователь успешно зарегистрирован!</h1>

<p>Теперь необходимо авторизоваться по <a href="{% url 'users:login' %}">ссылке</a></p>
{% endblock %}